#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-pdocs
Version  : 1.1.1
Release  : 1
URL      : https://files.pythonhosted.org/packages/e0/24/525a8fc144a0c25cc7e571e64cb37050b581f574aa518137f9d0deca3933/pdocs-1.1.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/e0/24/525a8fc144a0c25cc7e571e64cb37050b581f574aa518137f9d0deca3933/pdocs-1.1.1.tar.gz
Summary  : A simple program and library to auto generate API documentation for Python modules.
Group    : Development/Tools
License  : MIT
Requires: pypi-pdocs-bin = %{version}-%{release}
Requires: pypi-pdocs-python = %{version}-%{release}
Requires: pypi-pdocs-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry)

%description
[![pdocs - Documentation Powered by Your Python Code.](https://raw.github.com/timothycrosley/pdocs/master/art/logo_large.png)](https://timothycrosley.github.io/pdocs/)
_________________

%package bin
Summary: bin components for the pypi-pdocs package.
Group: Binaries

%description bin
bin components for the pypi-pdocs package.


%package python
Summary: python components for the pypi-pdocs package.
Group: Default
Requires: pypi-pdocs-python3 = %{version}-%{release}

%description python
python components for the pypi-pdocs package.


%package python3
Summary: python3 components for the pypi-pdocs package.
Group: Default
Requires: python3-core
Provides: pypi(pdocs)
Requires: pypi(docstring_parser)
Requires: pypi(hug)
Requires: pypi(mako)
Requires: pypi(markdown)

%description python3
python3 components for the pypi-pdocs package.


%prep
%setup -q -n pdocs-1.1.1
cd %{_builddir}/pdocs-1.1.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641525387
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/pdocs

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
